version: '3.7'

networks:
  backend:
    driver: bridge

volumes:
  mysql:
    driver: local

services:
  php:
    image: os2forms/os2forms8:${OS2FORMS8_TAG}
    env_file:
      - .env
    ports:
      - ${WEB_SERVER_PORT}:80
    volumes:
      - ./simplesamlphp:/opt/drupal/simplesamlphp
    depends_on:
      - mariadb
    networks:
      - backend
    restart: always

  mariadb:
    image: mariadb:latest
    env_file:
      - .env
    volumes:
      - .docker/mariadb/data:/var/lib/mysql:delegated
      - .docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf:ro,delegated
    networks:
      - backend
    restart: always
