<?php

/**
 * @file
 * OS2Forms Address autocomplete functionality module.
 */

/**
 * Implements hook_webform_migrate_d7_webform_element_ELEMENT_TYPE_alter().
 *
 * Not released hook.
 *
 * @See https://www.drupal.org/project/webform_migrate/issues/3155073
 */
function os2forms_dawa_webform_migrate_d7_webform_element_address_autocomp_alter(&$markup, $indent, array $element) {
  $markup .= "$indent  '#type': os2forms_dawa_address\n";
}

/**
 * Implements hook_webform_migrate_d7_webform_element_ELEMENT_TYPE_alter().
 *
 * Not released hook.
 *
 * @See https://www.drupal.org/project/webform_migrate/issues/3155073
 */
function os2forms_dawa_webform_migrate_d7_webform_element_addrs_autocomp_l_alter(&$markup, $indent, array $element) {
  $markup .= "$indent  '#type': os2forms_dawa_address_matrikula\n";
}
