language: php

sudo: false

php:
  - 7.2

install:
  - composer global require drush/drush:8.x-dev drupal/coder mglaman/drupal-check friendsoftwig/twigcs
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - phpcs --config-set installed_paths ../../drupal/coder/coder_sniffer
  - phpenv rehash
  - nvm install node
  - nvm use node
  - npm install --global yarn
  - cd ../ && composer create-project drupal-composer/drupal-project:8.x-dev drupal --no-interaction
  - cd drupal
  - DRUPAL_ROOT=$(pwd)/web
  - export REPOSITORIES='"repositories":\ \['
  - export REPOSITORIES_REPLACE='"repositories":\[\{"type":"path","url":"..\/os2web_simplesaml_checklist","options":\{"symlink":false\}\},'
  - export REQUIRE='"require":\ {'
  - export REQUIRE_REPLACE='"require":{"os2web\/os2web_simplesaml_checklist":"\*",'
  - sed -i "s/$REPOSITORIES/$REPOSITORIES_REPLACE/g" composer.json
  - sed -i "s/$REQUIRE/$REQUIRE_REPLACE/g" composer.json
  - composer update os2web/os2web_simplesaml_checklist
  - PROJECT_PATH=$DRUPAL_ROOT/modules/contrib/os2web_simplesaml_checklist
  - cd $DRUPAL_ROOT/core
  - yarn install
  - npm install --global eslint-config-drupal-bundle stylelint

script:
  - phpcs --standard=Drupal --ignore=*.md $PROJECT_PATH
  - twigcs $PROJECT_PATH
  - cd $DRUPAL_ROOT/core
  - eslint $PROJECT_PATH
  - stylelint --aei $PROJECT_PATH/**/*.css
  - drupal-check $PROJECT_PATH
