<?php

/**
 * @file
 * OS2Web implementation of the Checklist API.
 */

use Drupal\Core\Url;

/**
 * Implements hook_checklistapi_checklist_info().
 *
 * Defines a checklist based on
 * @link http://buytaert.net/drupal-learning-curve Dries Buytaert's Drupal learning curve @endlink
 * .
 */
function os2web_simplesaml_checklist_checklistapi_checklist_info() {
  $definitions = [];
  $definitions['os2web_simplesaml_checklist'] = [
    '#title' => t('OS2Web SimpleSAML Checklist'),
    '#path' => '/admin/config/people/os2web-simplesaml-checklist',
    '#callback' => 'os2web_simplesaml_checklist_checklistapi_checklist_items',
    '#description' => t('Configure your SimpleSAML'),
    '#help' => '<p>' . t("Check off each SimpleSAML related task as you complete it. Don't forget to click the <em>Save</em> button!") . '</p>',
    '#storage' => 'state',
  ];
  return $definitions;
}

/**
 * Implements callback_checklistapi_checklist_items() for example_checklist.
 */
function os2web_simplesaml_checklist_checklistapi_checklist_items() {
  $moduleHandler = \Drupal::service('module_handler');
  $installation_full_url = \Drupal::request()->getSchemeAndHttpHost() . base_path();
  $installation_full_https = 'https://' . \Drupal::request()->getHost() . base_path();

  $introduction_tab = [
    '#theme' => 'os2forms_simplesaml_checklist_intro_tab',
  ];

  $troubleshooting_tab = [
    '#theme' => 'os2forms_simplesaml_checklist_troubleshoot_tab',
  ];

  $definitions = [
    // Introduction.
    'introduction' => [
      '#title' => t('Introduction'),
      '#description' => \Drupal::service('renderer')->render($introduction_tab),
    ],

    // SimpleSAML install and configure.
    'simplesamlphp' => [
      '#title' => t('Install SimpleSAMLphp'),
      '#description' => '<p>' . t('Steps description how to download, install and configure SimpleSAMLphp installation.') . '</p>',
      'simplesamlphp_install' => [
        '#title' => t('Download and install SimpleSAMLphp.'),
        '#description' => t('Follow the official guide on how to install SimpleSAML.'),
        'download' => [
          '#text' => t('Download'),
          '#url' => Url::fromUri('https://simplesamlphp.org/download'),
        ],
        'install' => [
          '#text' => t('Install'),
          '#url' => Url::fromUri('https://simplesamlphp.org/docs/stable/simplesamlphp-install'),
        ],
      ],
      'simplesamlphp_configure_endpoint' => [
        '#title' => t('Configure http endpoint for SimpleSAMLphp installation.'),
        '#description' => t('A normal workflow would be to expose SimpleSAML as @installation/simplesaml.', [
          '@installation' => substr($installation_full_url, 0, -1),
        ]),
        'configure_endpoint_apache' => [
          '#text' => t('Configure Apache'),
          '#url' => Url::fromUri('https://simplesamlphp.org/docs/stable/simplesamlphp-install#section_4'),
        ],
        'configure_endpoint_nginx' => [
          '#text' => t('Configure Nginx'),
          '#url' => Url::fromUri('https://simplesamlphp.org/docs/stable/simplesamlphp-install#section_5'),
        ],
      ],
      'simplesamlphp_https_endpoint' => [
        '#title' => t('Provide HTTPS certificate for SimpleSAMLphp installation endpoint.'),
        '#description' => t('A normal workflow would be to expose SimpleSAML as @installation/simplesaml.', [
          '@installation' => substr($installation_full_https, 0, -1),
        ]),
      ],
      'simplesamlphp_configure' => [
        '#title' => t('Configure SimpleSAMLphp installation.'),
        '#description' => t('Normally SimpleSAMLphp is to be used as SP (service provider).'),
        'configure_simplesamlphp' => [
          '#text' => t('Configure SimpleSAMLphp'),
          '#url' => Url::fromUri('https://simplesamlphp.org/docs/stable/simplesamlphp-install#section_6'),
        ],
        'configure_simplesamlphp_sp' => [
          '#text' => t('SimpleSAMLphp Service Provider QuickStart'),
          '#url' => Url::fromUri('https://simplesamlphp.org/docs/stable/simplesamlphp-sp'),
        ],
      ],
      'simplesamlphp_test' => [
        '#title' => t('Test a successful login via SimpleSAMLphp.'),
        '#description' => t('You should be able to login on @installation/simplesaml by selecting the configured authentication source.', [
          '@installation' => substr($installation_full_https, 0, -1),
        ]),
      ],
    ],

    // Configure simplesamlphp_auth module.
    'simplesamlphp_auth' => [
      '#title' => t('Install simplesamlphp_auth module'),
      '#description' => '<p>' . t('Download, install and configure simplesamlphp_auth Drupal module.') . '</p>',
      'simplesamlphp_auth_module_install' => [
        '#title' => t('Install simplesamlphp_auth (auto).'),
        '#description' => t('Download and install simplesamlphp_auth Drupal module.'),
        '#default_value' => $moduleHandler->moduleExists('simplesamlphp_auth'),
        'project_page' => [
          '#text' => t('Download'),
          '#url' => Url::fromUri('https://www.drupal.org/project/simplesamlphp_auth'),
        ],
        'modules_page' => [
          '#text' => t('Enable'),
          '#url' => Url::fromRoute('system.modules_list'),
        ],
      ],
      'simplesamlphp_auth_module_configure' => [
        '#title' => t('Configure simplesamlphp_auth.'),
        '#description' => t('Configure simplesamlphp_auth Drupal module.'),
        'project_page' => [
          '#text' => t('Configure'),
          '#url' => ($moduleHandler->moduleExists('simplesamlphp_auth')) ? Url::fromRoute('simplesamlphp_auth.admin_settings') : Url::fromRoute('system.modules_list'),
        ],
      ],
      'simplesamlphp_auth_activate' => [
        '#title' => t('Activate authentication via SimpleSAMLphp (auto).'),
        '#description' => t('Doing that before configuring the module could lock you out of Drupal..'),
        '#default_value' => (\Drupal::hasService('simplesamlphp_auth.manager')) ? \Drupal::service('simplesamlphp_auth.manager')
          ->isActivated() : FALSE,
        'project_page' => [
          '#text' => t('Configure'),
          '#url' => ($moduleHandler->moduleExists('simplesamlphp_auth')) ? Url::fromRoute('simplesamlphp_auth.admin_settings') : Url::fromRoute('system.modules_list'),
        ],
      ],
    ],

    // Enable installation HTTPS certificate.
    'installation_https' => [
      '#title' => t('HTTPS certificate (production website)'),
      '#description' => '<p>' . t('In order for SimpleSAMLphp to work securely, website must be using HTTPS certificate.') . '</p>',
      'installation_https_enable' => [
        '#title' => t('Enable HTTPS certificate (auto).'),
        '#description' => t('Configure your host to use HTTPS certificate.'),
        '#default_value' => \Drupal::request()->isSecure(),
      ],
    ],

    // Configure os2forms_simplesaml module.
    'os2web_simplesaml' => [
      '#title' => t('Install os2web_simplesaml module'),
      '#description' => '<p>' . t('Install and configure os2web_simplesaml Drupal module.') . '</p>',
      'os2web_simplesaml_install' => [
        '#title' => t('Install os2web_simplesaml (auto).'),
        '#description' => t('Install os2web_simplesaml Drupal module.'),
        '#default_value' => $moduleHandler->moduleExists('os2web_simplesaml'),
        'modules_page' => [
          '#text' => t('Enable'),
          '#url' => Url::fromRoute('system.modules_list'),
        ],
      ],
      'os2web_simplesaml_ips' => [
        '#title' => t("Provide IP's list to redirect SimpleSAML login (optional)."),
        'project_page' => [
          '#text' => t('Configure'),
          '#url' => ($moduleHandler->moduleExists('simplesamlphp_auth')) ? Url::fromRoute('simplesamlphp_auth.admin_settings_local') : Url::fromRoute('system.modules_list'),
        ],
      ],
    ],

    // Troubleshooting.
    'troubleshooting' => [
      '#title' => t('Troubleshooting'),
      '#description' => \Drupal::service('renderer')->render($troubleshooting_tab),
    ],
  ];
  return $definitions;
}

/**
 * Implements hook_theme().
 */
function os2web_simplesaml_checklist_theme($existing, $type, $theme, $path) {
  return [
    'os2forms_simplesaml_checklist_intro_tab' => [
      'template' => 'os2forms-simplesaml-checklist-intro-tab',
    ],
    'os2forms_simplesaml_checklist_troubleshoot_tab' => [
      'template' => 'os2forms-simplesaml-checklist-troubleshoot-tab',
    ],
  ];
}
