#!/usr/bin/env bash
# Script reinstalling drupal from scratch based in os2forms_forloeb_profile.

# Trapping CTRL-C
trap ctrl_c INT
trap ctrl_c SIGINT
trap ctrl_c SIGTERM

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

# Helper functions for console output
echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

echo-yellow "Updating os2forms_forloeb module"
fin composer update os2forms/os2forms_forloeb

echo-yellow "Updating composer.lock file"
fin composer update --lock

echo-yellow "Fetching composer dependencies"
fin composer install

echo-yellow "Installing drupal based on os2forms_forloeb_profile"
if ! fin drush status bootstrap | grep -q Successful ; then
    echo "Drupal is not bootstrapped - starting site-install"
    fin drush si os2forms_forloeb_profile --db-url=mysql://root:root@db/default --account-pass=admin --site-name=OS2forms_Forløb -y -v

    # Creating demo-users - BEGIN

    fin drush ucrt forloeb-designer --mail="os2forms-forloeb-designer@example.com" --password="forloeb-designer"
    fin drush urol "forloeb_designer" forloeb-designer

    fin drush ucrt flow-designer --mail="os2forms-flow-designer@example.com" --password="flow-designer"
    fin drush urol "flow_designer" flow-designer

    fin drush ucrt medarbejder --mail="os2forms-medarbejder@example.com" --password="medarbejder"
    fin drush urol "medarbejder" medarbejder

    fin drush ucrt sagsbehandler --mail="os2forms-sagsbehandler@example.com" --password="sagsbehandler"
    fin drush urol "sagsbehandler" sagsbehandler

    fin drush ucrt leder --mail="os2forms-leder@example.com" --password="leder"
    fin drush urol "leder" leder

    fin drush ucrt borger --mail="os2forms-borger@example.com" --password="borger"
    fin drush urol "borger" borger

    fin drush ucrt virksomhed --mail="os2forms-virksomhed@example.com" --password="virksomhed"
    fin drush urol "virksomhed" virksomhed

    # Creating demo-users - END

    # Import of user interface translations. Never check for updates. Only use local translation source. Only overwrite imported translations.
    # Comment out the three lines to run install without importing translations
    fin drush locale-check
    fin drush locale-update
    # End import og translations

else
    echo "Drupal already bootstrapped - skipping install"
fi

echo-yellow "Install os2forms_forloeb, run update.php and clear caches"
fin drush en os2forms_forloeb -y
fin drush updb -y
fin drush cr
