#!/usr/bin/env bash
# Script reinstalling drupal from scratch based in os2web profile.

# Trapping CTRL-C
trap ctrl_c INT
trap ctrl_c SIGINT
trap ctrl_c SIGTERM

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

# Helper functions for console output
echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

echo-yellow "Fetching composer dependencies"
fin composer install

echo-yellow "Installing drupal based on os2web profile"
fin drush si os2core --db-url=mysql://root:root@db/default --account-pass=admin -y -vvv

echo-yellow "Enable modules"
fin drush en os2forms os2forms_nemid os2forms_dawa os2forms_sbsys -y
