<?php

/**
 * @file
 * OS2Web SimpleSAML functionality module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds redirect IPs settings to simplesamlphp_auth_local_settings_form.
 */
function os2web_simplesaml_form_simplesamlphp_auth_local_settings_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $config = \Drupal::config('os2web_simplesaml.settings');

  $form['os2web_simplesaml_additional_settings'] = [
    '#type' => 'fieldset',
    '#title' => t('OS2Web SimpleSAML additional settings'),
  ];
  $form['os2web_simplesaml_additional_settings']['redirect_ips'] = [
    '#type' => 'textfield',
    '#title' => t("Redirect IP's to SimpleSAML login"),
    '#default_value' => $config->get('redirect_ips'),
    '#description' => t('Comma separated. Ex. 192.168.1.1,192.168.2.1'),
  ];
  $form['os2web_simplesaml_additional_settings']['redirect_trigger_path'] = [
    '#type' => 'textfield',
    '#title' => t('Redirect triggering paths'),
    '#default_value' => $config->get('redirect_trigger_path'),
    '#description' => t('Comma separated paths that will trigger the redirect The \'*\' character is a wildcard. Ex. /form/*,/node/add/webform NB! The caching for that path will be programmatically disabled.'),
  ];
  $form['os2web_simplesaml_additional_settings']['redirect_cookies_ttl'] = [
    '#type' => 'number',
    '#min' => 0,
    '#step' => 10,
    '#title' => t('Redirect cookies time to live (TTL)'),
    '#default_value' => $config->get('redirect_cookies_ttl'),
    '#description' => t('Number of seconds, after which the positive or negative redirect decision will expire. Setting long time improves the performance, but IP rules change will take longer to become active for all users.'),
    '#required' => TRUE,
  ];

  $form['#validate'][] = 'os2web_simplesaml_form_validate';
  $form['#submit'][] = 'os2web_simplesaml_form_submit';
}

/**
 * Validation for simplesamlphp_auth_local_settings_form.
 *
 * Checks provided IP list format.
 */
function os2web_simplesaml_form_validate(&$form, FormStateInterface $form_state) {
  if ($form_state->hasValue('redirect_ips')) {
    $redirect_ips = $form_state->getValue('redirect_ips');
    if (preg_match("/[^0-9.,]/", $redirect_ips)) {
      $form_state->setErrorByName('redirect_ips', t('Invalid format, must be comma separated. Ex. 192.168.1.1,192.168.2.1'));
    }
  }
 }

/**
 * Submit for simplesamlphp_auth_local_settings_form.
 *
 * Saves redirect_ips into configuration.
 */
function os2web_simplesaml_form_submit(&$form, FormStateInterface $form_state) {
  $redirect_ips = $form_state->getValue('redirect_ips');
  $redirect_trigger_path = $form_state->getValue('redirect_trigger_path');
  $redirect_cookies_ttl = $form_state->getValue('redirect_cookies_ttl');

  $config = \Drupal::service('config.factory')
    ->getEditable('os2web_simplesaml.settings');
  $config->set('redirect_ips', $redirect_ips);
  $config->set('redirect_trigger_path', $redirect_trigger_path);
  $config->set('redirect_cookies_ttl', $redirect_cookies_ttl);
  $config->save();

  // Invalidating router cache, so that new settings are applied.
  \Drupal::service("router.builder")->rebuild();
}

/**
 * Implements hook_entity_extra_field_info().
 */
function os2web_simplesaml_entity_extra_field_info() {
  $fields = [];
  $fields['user']['user']['form']['os2web_simplesaml_uid'] = [
    'label' => t('SimpleSAML UID'),
    'description' => '',
    'weight' => 0,
    'visible' => TRUE,
  ];
  return $fields;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see AccountForm::form()
 * @see os2web_simplesaml_user_form_includes()
 */
function os2web_simplesaml_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  os2web_simplesaml_user_form_includes($form);

  // If the user has a simplesamlphp_auth authmap record, then fetch it and
  // prefill the field.
  $authmap = \Drupal::service('externalauth.authmap');
  $account = $form_state->getFormObject()->getEntity();
  $authname = $authmap->get($account->id(), 'simplesamlphp_auth');
  if ($authname) {
    $form['os2web_simplesaml_uid']['#default_value'] = $authname;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see AccountForm::form()
 * @see os2web_simplesaml_user_form_includes()
 */
function os2web_simplesaml_form_user_register_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  os2web_simplesaml_user_form_includes($form);
}

/**
 * Helper function to include the BC SimpleSAML on user forms.
 *
 * Alters the user register form to include a textfield for providing custom
 * SimpleSAML value.
 *
 * @param array $form
 *   The user account form.
 *
 * @see os2web_simplesaml_user_form_submit()
 */
function os2web_simplesaml_user_form_includes(array &$form) {
  // Getting SimpleSAML existing authname to use as an example.
  $query = \Drupal::database()->select('authmap', 'am')
    ->fields('am', ['authname'])
    ->condition('provider', 'simplesamlphp_auth')
    ->range(0, 1);
  $simplesamlExample = $query->execute()->fetchField();

  $form['os2web_simplesaml_uid'] = [
    '#type' => 'textfield',
    '#title' => t('SimpleSAML UID'),
    '#access' => \Drupal::currentUser()->hasPermission('change saml authentication setting'),
    '#description' => $simplesamlExample ? t('Example of the existing SimpleSAML entry from authmap table: <b>@simplesaml</b>', ['@simplesaml' => $simplesamlExample]) : t('Provide a string serves the UID of the user.'),
  ];

  // Adding custom validation.
  $form['#validate'][] = 'os2web_simplesaml_user_form_validate';

  // Adding custom submit.
  $form['actions']['submit']['#submit'][] = 'os2web_simplesaml_user_form_submit';
}

/**
 * Form validation handler for user_form.
 */
function os2web_simplesaml_user_form_validate($form, FormStateInterface $form_state) {
  $simplesaml_uid = NULL;
  if ($form_state->getValue('os2web_simplesaml_uid')) {
    $simplesaml_uid = $form_state->getValue('os2web_simplesaml_uid');
  }

  if (!$form_state->getValue('simplesamlphp_auth_user_enable') && !empty($simplesaml_uid)) {
    $form_state->setErrorByName('os2web_simplesaml_uid', t('Field SimpleSAML UID is provided but SAML authentication is not checked, mapping will not be created'));
  }
}

/**
 * Form submission handler for user_form.
 */
function os2web_simplesaml_user_form_submit($form, FormStateInterface $form_state) {
  $authmap = \Drupal::service('externalauth.authmap');
  $externalauth = \Drupal::service('externalauth.externalauth');

  // Remove this user from the ExternalAuth authmap table.
  $authmap->delete($form_state->getValue('uid'));

  if ($form_state->getValue('os2web_simplesaml_uid')) {
    $simplesaml_uid = $form_state->getValue('os2web_simplesaml_uid');
  }

  // Add an authmap entry for this account, so it can leverage SAML
  // authentication.
  if ($simplesaml_uid) {
    $account = $form_state->getFormObject()->getEntity();
    $externalauth->linkExistingAccount($simplesaml_uid, 'simplesamlphp_auth', $account);
  }
}
