<?php

/**
 * @file
 * Contains hooks related to OS2Forms webform list module.
 */

/**
 * Implements hook_entity_type_alter().
 *
 * Change entitytypes.
 */
function os2forms_webform_list_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  // Define a new list builder classes.
  $entity_types['webform']->setListBuilderClass('Drupal\os2forms_webform_list\CustomWebformEntityListBuilder');
  $entity_types['maestro_template']->setListBuilderClass('Drupal\os2forms_webform_list\CustomMaestroTemplateEntityListBuilder');
}
