name: Deploy release to test.os2forms.dk
on:
  release:
    types: [created published]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          sh /var/www/test.os2forms.dk/private/os2forms_init/rebuild_installation.sh
